name: Auto Patch + Build NekoBox+

on:
  push:
    paths:
      - 'patches.tar.gz'
  workflow_dispatch:

jobs:
  patch-and-build:
    name: Apply Patches + Build
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем архив патчей
      - name: Download patches.tar.gz
        id: patch_step
        env:
          PATCH_URL: ${{ vars.PATCHES_TGZ_URL }}
          GH_TOKEN: ${{ github.token }} # Этот токен дает утилите gh права на отмену
        run: |
          # Запоминаем корень нашей рабочей зоны (абсолютный путь)
          ROOT_DIR="$GITHUB_WORKSPACE"
          # Если PATCH_URL задан, пробуем скачать (флаг --fail не даст скачать 14-байтную ошибку 404)
          if [ -n "$PATCH_URL" ]; then
            curl -L --fail -o patches.tar.gz "$PATCH_URL" || (echo "Файл по ссылке не найден.")
          fi
          if [ -f "patches.tar.gz" ]; then
            mkdir -p "$ROOT_DIR/patches"
            tar -xzvf patches.tar.gz -C "$ROOT_DIR/patches"
            echo "Архив успешно распакован."
            echo "patches_found=true" >> $GITHUB_OUTPUT
          else
            echo "Архив patches.tar.gz не найден. Выходим с успехом."
            # Записываем в специальную переменную GitHub, что патчей нет
            echo "patches_found=false" >> $GITHUB_OUTPUT
          fi
      # 2. Применяем ВСЕ патчи по заголовкам (Base + Target commit)
      - name: Apply all patches automatically
        if: steps.patch_step.outputs.patches_found == 'true'
        run: |
          # Запоминаем корень нашей рабочей зоны (абсолютный путь)
          ROOT_DIR="$GITHUB_WORKSPACE"
          mkdir -p "$GITHUB_WORKSPACE/workspace"
          cd "$GITHUB_WORKSPACE/patches"
          for patch in *.patch; do
            header=$(head -10 "$patch")
            base_not_clean=$(echo "$header" | grep -oP 'Base:\s*\K.*')
            base=$(echo "$base_not_clean" | grep -oP '^https://github\.com/[^/]+/[^/]+' | sed 's|/commits/.*||' | sed 's|\.git||' | tr -d ' \r')
            target=$(echo "$header" | grep -oP 'Target patch commit:\s*\K.*' || echo "main")
            
            dir=$(basename "$patch" .patch)
            
            if [ "$dir" = "NekoBoxForAndroid" ]; then
              dir="NekoBoxForAndroid"
            elif [ "$dir" = "sing-box" ]; then
              dir="sing-box"
            elif [ "$dir" = "libneko" ]; then
              dir="libneko"
            elif [ "$dir" = "sing-vmess" ]; then
              dir="sing-vmess"
            elif [ "$dir" = "MasterDnsVPN" ]; then
              dir="MasterDnsVPN-plus"
            elif [ "$dir" = "amneziawg-go" ]; then
              dir="amneziawg-go"
            elif [ "$dir" = "net" ]; then
              dir="net"
            else
              continue
            fi

            mkdir -p upstream/$dir
            git clone --depth 1 "$base" "upstream/$dir"
            cd "upstream/$dir"
            git fetch --depth 1 origin "$target"
            git checkout "$target"
            cd ../..
            cp -r "upstream/$dir" "$GITHUB_WORKSPACE/workspace/$dir"
            cd "$GITHUB_WORKSPACE/workspace/$dir"
            git apply "$GITHUB_WORKSPACE/patches/$patch" || echo "⚠️ $patch не применился (уже применён)"
            cd "$GITHUB_WORKSPACE/patches"
          done
          # echo "patches_found=false" >> $GITHUB_OUTPUT

          cd "$GITHUB_WORKSPACE/workspace"

          git clone "https://github.com/amnezia-vpn/amneziawg-go.git" "amneziawg-go"
          if [ -f "sing-box/patches/amneziawg-go/README" ]; then
            cd amneziawg-go
            header=$(head -6 "../sing-box/patches/amneziawg-go/README")
            target=$(echo "$header" | grep -oP '2. Checkout to\s*\K.*')
            git checkout "$target"
            git apply ../sing-box/patches/amneziawg-go/*.patch
            cd ..
          else
            echo "Папка патчей x-slash-net отсутствует, пропускаем шаг для библиотеки amneziawg-go."
          fi

          git clone "https://github.com/metacubex/utls" "utls"
          if [ -f "sing-box/patches/utls/README" ]; then
            cd utls
            header=$(head -6 "../sing-box/patches/utls/README")
            target=$(echo "$header" | grep -oP '2. Checkout to\s*\K.*')
            git checkout "$target"
            git apply ../sing-box/patches/utls/*.patch
            cd ..
          else
            echo "Папка патчей x-slash-net отсутствует, пропускаем шаг для библиотеки utls."
          fi

          git clone https://go.googlesource.com/net net
          if [ -f "sing-box/patches/x-slash-net/README" ]; then
            cd net
            header=$(head -6 "../sing-box/patches/x-slash-net/README")
            target=$(echo "$header" | grep -oP '2. Checkout to\s*\K.*')
            git checkout "$target"
            git apply ../sing-box/patches/x-slash-net/*.patch
            cd ..
          else
            echo "Папка патчей x-slash-net отсутствует, пропускаем шаг для библиотеки net."
          fi

          cd NekoBoxForAndroid

          export ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"
          export ANDROID_SDK_ROOT="$ANDROID_HOME"
          export JAVA_HOME=/opt/android-studio/jbr

          bash buildScript/lib/assets.sh
          bash buildScript/lib/core.docker.sh

          cd ..

          cd ..

      # 3. Создаём архив с патченными репозиториями
      - name: Create patched repositories archive
        if: steps.patch_step.outputs.patches_found == 'true'
        run: |
          pwd
          ls -F -1
          ls -F -1 patches/upstream
          tar -czf NekoBoxPlus.tar.gz patches workspace
          echo "Patched archive created: NekoBoxPlus.tar.gz"
      
      # 4.Загружаем архив как артефакт (доступен в GitHub UI)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NekoBoxPlus
          path: NekoBoxPlus.tar.gz
      
      # 5. Собираем libcore.aar (главный шаг после патчей)
      - name: Native Build (LibCore)
        if: steps.patch_step.outputs.patches_found == 'true' && 'true' == 'false'
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/25.0.8775105" >> local.properties
          
          ./run lib core

      # 6. Инициализируем Gradle
      - name: Init Gradle
        if: steps.patch_step.outputs.patches_found == 'true' && 'true' == 'false'
        run: |
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./run init action gradle

      # 7. Финальная сборка APK
      - name: Assemble Release
        if: steps.patch_step.outputs.patches_found == 'true' && 'true' == 'false'
        run: |
          KEYSTORE_PASS="${{ secrets.KEYSTORE_PASS }}" \
          ALIAS_NAME="${{ secrets.ALIAS_NAME }}" \
          ALIAS_PASS="${{ secrets.ALIAS_PASS}}" \
          ./gradlew app:assembleOssRelease
          
          APK=$(find app/build/outputs/apk -name '*arm64-v8a*.apk')
          APK=$(dirname $APK)
          echo "APK=$APK" >> $GITHUB_ENV

      # 8. Загружаем артефакт
      - name: Upload Artifacts
        if: steps.patch_step.outputs.patches_found == 'true' && 'true' == 'false'
        uses: actions/upload-artifact@v5
        with:
          name: NekoBoxPlus
          path: ${{ env.APK }}
